### ISSUE TITLE
Handle Force Exit Exception

### ISSUE THREAD

**Issue by J0shuaLeong** [AY2324S1-CS2113-W12-4/tp#152]
Save data even if user force quits

**Comment by ICubE-** [comment]
https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/util/Scanner.html#nextLine()
https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/util/NoSuchElementException.html
