### ISSUE TITLE
[PE-D][Tester E] UG does not cover opening query about health data

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-4/tp#164]
UG does not mention that once opened, the app will ask for user height, weight and calorie limit.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: nihalzp/ped#2

**Comment by ICubE-** [comment]
Duplicate of #161

**Comment by ICubE-** [comment]
Duplicate of #162
