### ISSUE TITLE
[PE-D][Tester E] Reordering of argument given to a command is not allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-4/tp#172]
`editprofile w/500 h/2000 l/1000`

This is not allowed by the current code, but this is:

`editprofile h/2000 w/500 l/1000`

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: nihalzp/ped#4

**Comment by J0shuaLeong** [comment]
The user guide specifies the format. Please follow the given format. Using other format will of course not be allowed, for that is how the application is made.
