### ISSUE TITLE
[PE-D][Tester B] No purpose for daily calorie limit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-4/tp#208]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/TriciaBK/ped/main/files/9b9db724-bc36-42a3-8ca0-e4b535bf976c.png)

if there a purpose for daily calorie limit in the profile? will users be informed if they have exceed their limit for a specific day?

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: TriciaBK/ped#12

**Comment by NgLixuanNixon** [comment]
Used in caloriebalance
