### ISSUE TITLE
As a user, I want to save my profile settings.

### ISSUE THREAD

**Issue by J0shuaLeong** [AY2324S1-CS2113-W12-4/tp#82]
Save user profile settings upon exiting application or if user enters "save"
Load settings into user profile so that user does not have to keep entering the details each time

**Comment by ICubE-** [comment]
What about storing all the input that user has given?

**Comment by J0shuaLeong** [comment]
> What about storing all the input that user has given? (like meals and workouts)

Sure, should we add on those in v2.1 or just do it for v2.0 as well.

**Comment by ICubE-** [comment]
> Sure, should we add on those in v2.1 or just do it for v2.0 as well.

I guess v2.1 is really not for adding features, so we should decide whether to implement on v2.0 or not.

**Comment by J0shuaLeong** [comment]
> > Sure, should we add on those in v2.1 or just do it for v2.0 as well.
> 
> I guess v2.1 is really not for adding features, so we should decide whether to implement on v2.0 or not.

Ok, possible to save profile data, and meals and workouts in two separate files? So when loading the file contents in it will be easier. One would load to userprofile the other to the meals and workouts list

**Comment by ICubE-** [comment]
> Ok, possible to save profile data, and meals and workouts in two separate files? So when loading the file contents in it will be easier. One would load to userprofile the other to the meals and workouts list

Cool. You can separate meals and workouts too.

**Comment by J0shuaLeong** [comment]
> > Ok, possible to save profile data, and meals and workouts in two separate files? So when loading the file contents in it will be easier. One would load to userprofile the other to the meals and workouts list
> 
> Cool. You can separate meals and workouts too.

Sure! Thanks
